<a href="https://colab.research.google.com/github/anvithagangineni/portfolio/blob/main/recommendation_systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
dataset=pd.read_csv('/content/drive/MyDrive/datasets/updated_steamgames.csv')
dataset

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Unnamed: 0,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,0,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,1,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,2,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,3,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,4,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,app,Squarism,SQUARISM is a minimalist logic game about comb...,NaN,"Positive,(15),- 100% of the 15 user reviews fo...","Nov 21, 2017","KirUn,algamedev,Alexander M","KirUn,KirUn","Indie,Casual,Puzzle","Single-player,Steam Achievements,Steam Cloud","English,French,German,Portuguese - Brazil,Simp...",27.0,"Casual,Indie",About This Game Square is life! This is a mi...,NaN,NaN,NaN,$2.99,NaN
9996,9996,app,Dandara OST🎵,NaN,NaN,"1 user reviews,- Need more user reviews to gen...","Feb 6, 2018",Long Hat House,"Raw Fury,Raw Fury","Action,Indie","Single-player,Downloadable Content,Steam Achie...","English,Japanese,French,German,Spanish - Spain...",NaN,"Action,Indie",About This Content 1. Dandara's Purpose (03:1...,NaN,NaN,NaN,$6.99,$17.58
9997,9997,app,Rumu - Soundtrack,NaN,NaN,"1 user reviews,- Need more user reviews to gen...","Dec 14, 2017",Robot House,"Hammerfall Publishing,Hammerfall Publishing","Adventure,Indie,Casual","Single-player,Downloadable Content",English,NaN,"Adventure,Casual,Indie",About This Content This is the gripping origi...,NaN,"Minimum:,Storage:,900 MB available space,Minim...","Recommended:,Storage:,900 MB available space,R...",$4.99,$14.98
9998,9998,app,Tannenberg - Supporter Edition Upgrade,NaN,NaN,"Positive,(40),- 100% of the 40 user reviews fo...","Nov 16, 2017","Blackmill Games,M2H","M2H,M2H","Action,Indie,Violent,Strategy","Multi-player,Online Multi-Player,Online Co-op,...",English,NaN,"Action,Indie,Strategy",About This Content The encouragement and back...,Mature Content Description The developers de...,"Minimum:,OS:,Windows Vista/7/8/10,Processor:,I...","Recommended:,OS:,Windows 10,Memory:,8 GB RAM,G...",$4.99,$42.46
9999,9999,app,Rail Recon,Delve into the underground facility of Rail Re...,NaN,"Positive,(23),- 95% of the 23 user reviews for...","Jan 23, 2018",Triggered Studios,"Triggered Studios,NHTV Breda University of App...","Indie,Action,Adventure","Single-player,Partial Controller Support",English,NaN,"Action,Adventure,Indie",About This Game Objective Started … Preparin...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",Free,NaN

In [ ]:
dataset=dataset.drop(['url'],axis=1)
dataset

,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40828,app,Rocksmith® 2014 Edition – Remastered – Sabaton...,NaN,NaN,NaN,"Feb 12, 2019",Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Ghost Division"" by S...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40829,app,Rocksmith® 2014 Edition – Remastered – Stone T...,NaN,NaN,NaN,"Feb 5, 2019",Ubisoft - San Francisco,NaN,"Casual,Simulation","Single-player,Shared/Split Screen,Downloadable...","English,German,French,Italian,Spanish - Spain,...",NaN,"Casual,Simulation","About This Content Play ""Trippin’ on a Hole i...",NaN,"Minimum:,OS:,Windows Vista, Windows 7, Windows...","Recommended:,OS:,Windows Vista, Windows 7, Win...",$2.99,NaN
40830,app,Fantasy Grounds - Quests of Doom 4: A Midnight...,NaN,NaN,NaN,"Jul 31, 2018","SmiteWorks USA, LLC",NaN,"RPG,Indie,Strategy,Software,Turn-Based,Fantasy...","Multi-player,Co-op,Cross-Platform Multiplayer,...",English,NaN,"Indie,RPG,Strategy",About This Content Quests of Doom 4: A Midni...,NaN,"Minimum:,OS:,Windows 7x , 8x or 10x,Processor:...","Recommended:,OS:,Windows 7x , 8x or 10x,Proces...",$7.99,NaN
40831,app,Mega Man X5 Sound Collection,NaN,NaN,NaN,"Jul 24, 2018","CAPCOM CO., LTD","CAPCOM CO., LTD,CAPCOM CO., LTD",Action,"Single-player,Downloadable Content,Steam Achie...","English,French,Italian,German,Spanish - Spain,...",NaN,Action,About This Content Get equipped with the stun...,NaN,"Minimum:,OS:,WINDOWS® 7 (64bit),Processor:,Int...","Recommended:,OS:,WINDOWS®10 (64bit),Processor:...",$9.99,NaN
40832,app,Stories In Stone,An RPG about a tribe exploring an ancient worl...,NaN,NaN,"Aug 8, 2018","16 Bit Psych,Kyle B","Self-Publish,Self-Publish","RPG,Adventure","Single-player,Partial Controller Support,Profi...",English,NaN,"Adventure,RPG",About This Game An RPG about a tribe explori...,NaN,NaN,NaN,$4.99,$2.80

In [ ]:
features_list=dataset['name']+dataset['genre']+dataset['game_description']+dataset['popular_tags']+dataset['game_details']
features_list=features_list.fillna('')

In [ ]:
for i in range(5000,10000):
  dataset.drop(index=i,inplace=True)

In [ ]:
path='/content/drive/MyDrive/datasets/updated_steamgames.csv'
dataset.to_csv(path)

In [ ]:
dataset

,Unnamed: 0,types,name,desc_snippet,recent_reviews,all_reviews,release_date,developer,publisher,popular_tags,game_details,languages,achievements,genre,game_description,mature_content,minimum_requirements,recommended_requirements,original_price,discount_price
0,0,app,DOOM,Now includes all three premium DLC packs (Unto...,"Very Positive,(554),- 89% of the 554 user revi...","Very Positive,(42,550),- 92% of the 42,550 use...","May 12, 2016",id Software,"Bethesda Softworks,Bethesda Softworks","FPS,Gore,Action,Demons,Shooter,First-Person,Gr...","Single-player,Multi-player,Co-op,Steam Achieve...","English,French,Italian,German,Spanish - Spain,...",54.0,Action,"About This Game Developed by id software, the...",NaN,"Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...","Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...",$19.99,$14.99
1,1,app,PLAYERUNKNOWN'S BATTLEGROUNDS,PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...,"Mixed,(6,214),- 49% of the 6,214 user reviews ...","Mixed,(836,608),- 49% of the 836,608 user revi...","Dec 21, 2017",PUBG Corporation,"PUBG Corporation,PUBG Corporation","Survival,Shooter,Multiplayer,Battle Royale,PvP...","Multi-player,Online Multi-Player,Stats","English,Korean,Simplified Chinese,French,Germa...",37.0,"Action,Adventure,Massively Multiplayer",About This Game PLAYERUNKNOWN'S BATTLEGROUND...,Mature Content Description The developers de...,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$29.99,NaN
2,2,app,BATTLETECH,Take command of your own mercenary outfit of '...,"Mixed,(166),- 54% of the 166 user reviews in t...","Mostly Positive,(7,030),- 71% of the 7,030 use...","Apr 24, 2018",Harebrained Schemes,"Paradox Interactive,Paradox Interactive","Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...","Single-player,Multi-player,Online Multi-Player...","English,French,German,Russian",128.0,"Action,Adventure,Strategy",About This Game From original BATTLETECH/Mec...,NaN,"Minimum:,Requires a 64-bit processor and opera...","Recommended:,Requires a 64-bit processor and o...",$39.99,NaN
3,3,app,DayZ,The post-soviet country of Chernarus is struck...,"Mixed,(932),- 57% of the 932 user reviews in t...","Mixed,(167,115),- 61% of the 167,115 user revi...","Dec 13, 2018",Bohemia Interactive,"Bohemia Interactive,Bohemia Interactive","Survival,Zombies,Open World,Multiplayer,PvP,Ma...","Multi-player,Online Multi-Player,Steam Worksho...","English,French,Italian,German,Spanish - Spain,...",NaN,"Action,Adventure,Massively Multiplayer",About This Game The post-soviet country of Ch...,NaN,"Minimum:,OS:,Windows 7/8.1 64-bit,Processor:,I...","Recommended:,OS:,Windows 10 64-bit,Processor:,...",$44.99,NaN
4,4,app,EVE Online,EVE Online is a community-driven spaceship MMO...,"Mixed,(287),- 54% of the 287 user reviews in t...","Mostly Positive,(11,481),- 74% of the 11,481 u...","May 6, 2003",CCP,"CCP,CCP","Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...","Multi-player,Online Multi-Player,MMO,Co-op,Onl...","English,German,Russian,French",NaN,"Action,Free to Play,Massively Multiplayer,RPG,...",About This Game,NaN,"Minimum:,OS:,Windows 7,Processor:,Intel Dual C...","Recommended:,OS:,Windows 10,Processor:,Intel i...",Free,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,app,KNIGHTS,KNIGHTS is a minimalist puzzle game based on a...,NaN,"Very Positive,(467),- 95% of the 467 user revi...","May 30, 2016",Arzola's,"Arzola's,Arzola's","Indie,Casual,Puzzle,Strategy,Chess,Minimalist,...","Single-player,Steam Achievements,Steam Trading...","English,French,Italian,German,Spanish - Spain,...",20.0,"Casual,Indie,Strategy",About This Game Overview KNIGHTS is a minima...,NaN,NaN,NaN,$0.99,$0.49
4996,4996,app,Cossacks: Art of War,Cossacks: The Art of War continues the history...,NaN,"Very Positive,(99),- 82% of the 99 user review...","Mar 31, 2002",GSC Game World,"GSC World Publishing,GSC World Publishing","Strategy,RTS,Historical,War",Single-player,English,NaN,Strategy,About This Game Cossacks: The Art of War – c...,NaN,NaN,NaN,$4.99,$54.45
4997,4997,bundle,Warframe Equinox Prime Access: Pacify & Provok...,Warframe Equinox Prime Access: Pacify & Provok...,NaN,NaN,NaN,Digital Extremes,NaN,NaN,"Single-player,Multi-player,Co-op,Downloadable ...","English, German, French, Italian, Korean, Span...",NaN,"Action,Free to Play",NaN,NaN,NaN,NaN,NaN,$79.99
4998,4998,app,Polandball: Can into Space!,Crazy fun rocket simulator game with countryba...,NaN,"Very Positive,(375),- 95% of the 375 user revi...","Jun 16, 2016",Alien Pixel Studios,"Alien Pixel Studios,Alien Pixel Studios","Memes,Casual,Indie,RPG,Political,Politics,Spac...","Single-player,Steam Achievements,Steam Trading...",English,22.0,"Casual,Indie,RPG",About This Game Your main objective is to hel...,NaN,"Minimum:,OS:,Windows 7 and above,Processor:,In...","Recommended:,OS:,Windows 7 and above,Processor...",$2.99,NaN
4999,4999,app,Camp Sunshine,Camp Sunshine is a 16-bit blood-soaked Horror ...,NaN,"Very Positive,(160),- 90% of the 160 user revi...","Oct 28, 2016",Fossil Games,"Fossil Games,Fossil Games","Indie,Casual,Action,Adventure,Horror,RPGMaker,...","Single-player,Steam Trading Cards,Captions ava...",English,NaN,"Action,Adventure,Casual,Indie",About This Game Camp Sunshine is a 16-bit blo...,NaN,NaN,NaN,$2.99,$5.37

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()

In [ ]:
vector=vectorizer.fit_transform(features_list)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosinesimilarity=cosine_similarity(vector)

In [ ]:
names=dataset['name'].values.tolist()
games=input('Enter game name:')
for i in names:
  if i==games:
    s=names.index(i)
print(s)

Enter game name:PLAYERUNKNOWN'S BATTLEGROUNDS
1

In [ ]:
similarity=list(enumerate(cosinesimilarity[s]))
print(similarity)

[(0, 0.12537786008891097), (1, 1.0000000000000002), (2, 0.0912625652781518), (3, 0.1080510615817161), (4, 0.12012450636456395), (5, 0.0), (6, 0.09197371722672044), (7, 0.07386813481272698), (8, 0.11076300071289512), (9, 0.11469261298857271), (10, 0.14685014626696033), (11, 0.04052193188606354), (12, 0.10751428497661301), (13, 0.09781068406019587), (14, 0.11558671979331092), (15, 0.0), (16, 0.12018546762764273), (17, 0.08014780721009122), (18, 0.15432318958263627), (19, 0.073172519335857), (20, 0.11109351539992936), (21, 0.058882358929344236), (22, 0.10728615394841404), (23, 0.117288568351024), (24, 0.10289865935254873), (25, 0.0), (26, 0.06288466792605125), (27, 0.08412812179421268), (28, 0.06788384135543052), (29, 0.05001978921721222), (30, 0.08489726102622794), (31, 0.04652728437569898), (32, 0.055581642659319905), (33, 0.07106085057577445), (34, 0.0991920467525396), (35, 0.10935267603970016), (36, 0.10095581335173964), (37, 0.05803642458211829), (38, 0.08850362603567755), (39, 0.0), (40, 0.11893547683197873), (41, 0.09437708203513279), (42, 0.10017674839182919), (43, 0.12221980992546944), (44, 0.0), (45, 0.0824920567568557), (46, 0.08549270307159175), (47, 0.0936074052825342), (48, 0.11670117275254174), (49, 0.09433963231147995), (50, 0.10031034789921159), (51, 0.07912894307323964), (52, 0.11701141039107989), (53, 0.08312596766788695), (54, 0.06041846668200935), (55, 0.09415261013671011), (56, 0.11769511302411313), (57, 0.0), (58, 0.05737506997905118), (59, 0.08742676880774251), (60, 0.07296022422501318), (61, 0.05449881572860068), (62, 0.10062327273289183), (63, 0.0), (64, 0.10025227110173231), (65, 0.30960541138597036), (66, 0.0), (67, 0.08712612812761723), (68, 0.0), (69, 0.08036541932315829), (70, 0.08564623499747138), (71, 0.062345592211495104), (72, 0.047706424443854006), (73, 0.12146562317250656), (74, 0.0), (75, 0.10734121513719645), (76, 0.08393639894333156), (77, 0.08846894450908295), (78, 0.05896696137376081), (79, 0.04562604309093693), (80, 0.08645290745656653), (81, 0.0), (82, 0.08371423994879788), (83, 0.08414507289718912), (84, 0.09242986962326312), (85, 0.1106192800576126), (86, 0.0), (87, 0.07024548234620467), (88, 0.09445490681611125), (89, 0.32597780504366347), (90, 0.07036050684477012), (91, 0.10793066966825826), (92, 0.06386887528851065), (93, 0.107684572071173), (94, 0.10887956773033432), (95, 0.12691684231013453), (96, 0.06586322036395514), (97, 0.06532161558412554), (98, 0.05481059212128844), (99, 0.07849587112219704), (100, 0.09119579419179723), (101, 0.1068930140228982), (102, 0.0), (103, 0.05872965962613693), (104, 0.06712969572856772), (105, 0.0), (106, 0.0), (107, 0.05453432519277588), (108, 0.07324287531622556), (109, 0.08413982778821572), (110, 0.058570754982685144), (111, 0.09483732350946522), (112, 0.0586853087834684), (113, 0.10860931610235812), (114, 0.0), (115, 0.06907399744920859), (116, 0.10719269171859087), (117, 0.12517564330467776), (118, 0.10689632690320391), (119, 0.0), (120, 0.0708086743459392), (121, 0.08125433818995702), (122, 0.11260110899427443), (123, 0.16093704034670558), (124, 0.06909635338405146), (125, 0.09454882159863066), (126, 0.1029061953719346), (127, 0.03932196030645745), (128, 0.06623515899476362), (129, 0.0820270296678489), (130, 0.10419080234122959), (131, 0.12318322744447467), (132, 0.12880992981066966), (133, 0.0), (134, 0.06572498039418334), (135, 0.0), (136, 0.11866766304572582), (137, 0.059417373805236005), (138, 0.03598705957761732), (139, 0.09109393687024488), (140, 0.049887269159392636), (141, 0.11205310047750795), (142, 0.08546533651906461), (143, 0.08116042364394753), (144, 0.11377013019778211), (145, 0.0), (146, 0.0), (147, 0.05432966315194764), (148, 0.08802557130173329), (149, 0.12275876464411171), (150, 0.11429449542993189), (151, 0.08282811825540626), (152, 0.1389512370665247), (153, 0.1258474724935111), (154, 0.08298212150930691), (155, 0.05280542712826384), (156, 0.09949638560851921), (157, 0.08024896901434567), (158, 0.1060485172573262), (159, 0.06505061585302456), (160, 0.05631931676524154), (161, 0.08321535915939605), (162, 0.09748499727987783), (163, 0.0), (164, 0.09671178356875348), (165, 0.1384331439182989), (166, 0.12362064889231099), (167, 0.034832887928731744), (168, 0.11741514236506366), (169, 0.0), (170, 0.07353202207905551), (171, 0.04666846704911563), (172, 0.0), (173, 0.0792252880836157), (174, 0.07227892118174603), (175, 0.08840783755118772), (176, 0.08190406340901576), (177, 0.05756512249500912), (178, 0.1180092824958443), (179, 0.05848636224321196), (180, 0.11874825711371623), (181, 0.06338720050161145), (182, 0.047484059846497326), (183, 0.12268746471212694), (184, 0.057812593457737364), (185, 0.10570443446076833), (186, 0.022699923530798576), (187, 0.10794386690293134), (188, 0.05892989358348776), (189, 0.07282304825173756), (190, 0.09009789444999011), (191, 0.0), (192, 0.0), (193, 0.14090032671484032), (194, 0.0799486049767203), (195, 0.11447838246727994), (196, 0.10233469755874924), (197, 0.08555850298140606), (198, 0.046541930736858), (199, 0.06418398814152236), (200, 0.08719843215275182), (201, 0.0795531658045575), (202, 0.09360920166414459), (203, 0.10127254963743045), (204, 0.0), (205, 0.1065587703659133), (206, 0.06921733221157882), (207, 0.0754988933076551), (208, 0.07003407650988137), (209, 0.0501073091658495), (210, 0.0796923621701506), (211, 0.0), (212, 0.06378800435547828), (213, 0.0), (214, 0.11035710450849569), (215, 0.12808587238633326), (216, 0.0), (217, 0.1121471490624159), (218, 0.0720381538145533), (219, 0.05880854669100504), (220, 0.07925017319995051), (221, 0.0895843004224428), (222, 0.11376177282223825), (223, 0.11070725491497564), (224, 0.08361381902026335), (225, 0.09471781208895656), (226, 0.11445092632055802), (227, 0.07129664629030505), (228, 0.06710990055707097), (229, 0.1248496107222197), (230, 0.0), (231, 0.0), (232, 0.13486109834486867), (233, 0.12696481036989807), (234, 0.10993145358492928), (235, 0.07397495596906209), (236, 0.11489039669643696), (237, 0.0), (238, 0.07956967708366475), (239, 0.07055917260978874), (240, 0.05301791649256897), (241, 0.0), (242, 0.08251865146730065), (243, 0.0774113337417304), (244, 0.0), (245, 0.07712648556406713), (246, 0.09693173577581769), (247, 0.06861111653363325), (248, 0.07240081793932647), (249, 0.09004302726192985), (250, 0.0), (251, 0.08618069500870916), (252, 0.10754501707196723), (253, 0.1016972529195597), (254, 0.07343714747151545), (255, 0.09429797468824132), (256, 0.06264821552045699), (257, 0.0633316687068811), (258, 0.07224328073108696), (259, 0.0), (260, 0.08347560345497647), (261, 0.07225552598837578), (262, 0.061703673053541595), (263, 0.07973042264175599), (264, 0.0), (265, 0.08451101205243491), (266, 0.0794410396239028), (267, 0.07792884079136225), (268, 0.04781175503077176), (269, 0.10599466977247905), (270, 0.09304705531258785), (271, 0.11914892635929632), (272, 0.05921508054211968), (273, 0.03418956029658648), (274, 0.06037307269244461), (275, 0.08968542632814139), (276, 0.07633134850981974), (277, 0.05166371561167501), (278, 0.09826690733765601), (279, 0.08341565529024475), (280, 0.08924756874426931), (281, 0.12918545555127114), (282, 0.09850917659316115), (283, 0.1281455458704588), (284, 0.0), (285, 0.07898577092520412), (286, 0.10071685095028442), (287, 0.03258315073854915), (288, 0.09022178495926403), (289, 0.08902196167235644), (290, 0.12417995580037308), (291, 0.0645572475936632), (292, 0.10334021154770769), (293, 0.07847455694956146), (294, 0.10462470974531567), (295, 0.11310229841080131), (296, 0.06939568392027948), (297, 0.11703294156216797), (298, 0.07205682241422887), (299, 0.1056099043662801), (300, 0.08593227925012874), (301, 0.1286320617694508), (302, 0.08596693500753354), (303, 0.10706090519969483), (304, 0.0939844356206706), (305, 0.11725693605666099), (306, 0.061508913177422506), (307, 0.05515152014208942), (308, 0.09497617189280727), (309, 0.04436214121923663), (310, 0.13188132666599553), (311, 0.1260912086137809), (312, 0.10729491854577904), (313, 0.08783819263633837), (314, 0.0939005415503903), (315, 0.07283395757033247), (316, 0.09102154267093401), (317, 0.10563833181369528), (318, 0.08675947605062145), (319, 0.0), (320, 0.087718197737629), (321, 0.03605665405465595), (322, 0.099490179851248), (323, 0.09558608369012467), (324, 0.05100378189087487), (325, 0.09682471696717947), (326, 0.09403091723970187), (327, 0.06857777025935677), (328, 0.06649939071451985), (329, 0.14681639555765402), (330, 0.05419338223709519), (331, 0.11708815495545144), (332, 0.08539851371279253), (333, 0.1135026077832193), (334, 0.06210750331444942), (335, 0.10439622771669374), (336, 0.10786958724821873), (337, 0.061985852614782), (338, 0.09419827127559072), (339, 0.1415048928097842), (340, 0.03969817521306206), (341, 0.11566000114142183), (342, 0.0769670988321612), (343, 0.1116855897646145), (344, 0.10090417914987124), (345, 0.11615074217896534), (346, 0.10880382528050613), (347, 0.09192488558335611), (348, 0.0), (349, 0.05143657928810997), (350, 0.061438518903679545), (351, 0.08343679498590259), (352, 0.08216438411380497), (353, 0.1472519207298885), (354, 0.09132374482959771), (355, 0.09052145197294514), (356, 0.06132598312770145), (357, 0.11464620720181386), (358, 0.0886849684302585), (359, 0.0), (360, 0.11930276924034983), (361, 0.06069818267071733), (362, 0.11562145119365234), (363, 0.12392478035371499), (364, 0.0588564411813248), (365, 0.05222321441671257), (366, 0.09174495077730532), (367, 0.11241438823278835), (368, 0.07223303257684213), (369, 0.0749494043875597), (370, 0.13120346368524502), (371, 0.06425864148279357), (372, 0.0750875830724276), (373, 0.10265807830113363), (374, 0.0855018930223403), (375, 0.11989899141422818), (376, 0.06270743464354292), (377, 0.1875336303486515), (378, 0.09825767986874276), (379, 0.0), (380, 0.06729476615258823), (381, 0.0627676673614054), (382, 0.07048834289024743), (383, 0.0), (384, 0.12088214047392266), (385, 0.13118267559441843), (386, 0.14024732995523564), (387, 0.053857475347012164), (388, 0.04946038114257562), (389, 0.05143994587586821), (390, 0.09101621867367835), (391, 0.14106504871420464), (392, 0.13188898306255484), (393, 0.09117770123181784), (394, 0.09931035123921318), (395, 0.08680772120508987), (396, 0.06988241907817443), (397, 0.07441803471082963), (398, 0.09666084791216525), (399, 0.09206938917748231), (400, 0.10203256809696694), (401, 0.12419313501381393), (402, 0.10204136357541393), (403, 0.0), (404, 0.06961789737904782), (405, 0.12806271216469797), (406, 0.16880394085345313), (407, 0.09047123482147415), (408, 0.0927197047958235), (409, 0.20326395369574407), (410, 0.08428134487553875), (411, 0.0850002930648554), (412, 0.08643616644543209), (413, 0.06706510532818832), (414, 0.10123306162673425), (415, 0.09879962102898178), (416, 0.11989879796616852), (417, 0.0), (418, 0.09308573942562379), (419, 0.10170822229799742), (420, 0.0), (421, 0.12250350270169047), (422, 0.10642488322247365), (423, 0.0), (424, 0.08281308653731856), (425, 0.0), (426, 0.11396738250760406), (427, 0.0731823455419523), (428, 0.12307270609099864), (429, 0.08417822792265572), (430, 0.022961715895787396), (431, 0.054598110260283765), (432, 0.06738823383050146), (433, 0.09243087667439609), (434, 0.07984825031798538), (435, 0.08807069074783767), (436, 0.09818164455072177), (437, 0.07509199173210643), (438, 0.06369510973646635), (439, 0.1096628544617252), (440, 0.08358340022540015), (441, 0.0696373256177943), (442, 0.10524588351224197), (443, 0.05873168282631266), (444, 0.07247259316237868), (445, 0.07398328214514874), (446, 0.08106785831677261), (447, 0.10592653092243191), (448, 0.08673590013806969), (449, 0.0), (450, 0.027044612124152184), (451, 0.06233627762286849), (452, 0.06443237162569443), (453, 0.0890757494353438), (454, 0.07831522179502512), (455, 0.13019734342384265), (456, 0.06571742531982844), (457, 0.03407903372498189), (458, 0.04589580771744832), (459, 0.11593814344108382), (460, 0.08590661526118729), (461, 0.14475293995591093), (462, 0.08720348942360008), (463, 0.09929411162787), (464, 0.0998780011015453), (465, 0.10978705526175177), (466, 0.0), (467, 0.14825090185367892), (468, 0.05464312416945951), (469, 0.06547813520969414), (470, 0.0448175406267117), (471, 0.07922925134479226), (472, 0.08277135685805963), (473, 0.12215832881152563), (474, 0.10256003929036174), (475, 0.07371520951807443), (476, 0.0430865556336453), (477, 0.06533149460177969), (478, 0.0), (479, 0.059716037432197534), (480, 0.10140014793349524), (481, 0.06529610479701138), (482, 0.13993458261449487), (483, 0.03020049960591766), (484, 0.05114467760796354), (485, 0.05627531876542088), (486, 0.0), (487, 0.03183675975239219), (488, 0.0758729213032245), (489, 0.08978147730648084), (490, 0.05794770615143494), (491, 0.07864157151085185), (492, 0.07876567868088291), (493, 0.04138118396629483), (494, 0.060149760021083826), (495, 0.12306783675390984), (496, 0.08218438517065613), (497, 0.12856418027458139), (498, 0.10496281013972877), (499, 0.09400756046081041), (500, 0.038844971156608135), (501, 0.0), (502, 0.08835323951831285), (503, 0.0904552422083676), (504, 0.08010291625330102), (505, 0.11304413422481698), (506, 0.0), (507, 0.056038004276216656), (508, 0.25159962560184157), (509, 0.02842460607376358), (510, 0.05465974469677547), (511, 0.12101184906588072), (512, 0.07791252655842468), (513, 0.11130598058950217), (514, 0.09229628788200371), (515, 0.11541529944321971), (516, 0.10969714484104658), (517, 0.1398773796300209), (518, 0.07157097666235265), (519, 0.075204727734427), (520, 0.08820793061289377), (521, 0.08323166617180988), (522, 0.051060103505835494), (523, 0.135926239732184), (524, 0.08464157377982404), (525, 0.08080535037413253), (526, 0.09074075389902937), (527, 0.05936126288156978), (528, 0.0), (529, 0.0), (530, 0.06313693269978646), (531, 0.09995128506167936), (532, 0.0), (533, 0.04905263543759023), (534, 0.0865691560357381), (535, 0.09706752237709236), (536, 0.054337835832234005), (537, 0.0970915351263253), (538, 0.06795406002169822), (539, 0.0), (540, 0.091316663303232), (541, 0.08327861268267635), (542, 0.0), (543, 0.12584820489801934), (544, 0.035010513447866466), (545, 0.07924586997790259), (546, 0.05505988078580729), (547, 0.08499704205475643), (548, 0.08219188212614699), (549, 0.05843751501023097), (550, 0.09693580498717187), (551, 0.0780200051037021), (552, 0.06835014756984864), (553, 0.04777372480355521), (554, 0.04892323039780836), (555, 0.06640836759203841), (556, 0.018097425011968885), (557, 0.10570514890142074), (558, 0.0667518699949507), (559, 0.0), (560, 0.0554709996697905), (561, 0.0), (562, 0.07026613634308017), (563, 0.05718645468383469), (564, 0.07505423343427912), (565, 0.0895281651583614), (566, 0.08229097366845343), (567, 0.0826803914456715), (568, 0.0), (569, 0.0), (570, 0.10443899770598192), (571, 0.07348270567309921), (572, 0.12330384501857902), (573, 0.08351575036110342), (574, 0.06177838536910505), (575, 0.04515335604091045), (576, 0.07026635514177605), (577, 0.06926920031694875), (578, 0.10446333847997673), (579, 0.08037397049535715), (580, 0.042231296277173064), (581, 0.06295541448571926), (582, 0.06191290209465833), (583, 0.1329413529745326), (584, 0.053153504252086294), (585, 0.058449732640221325), (586, 0.055419261537249374), (587, 0.07001853626735857), (588, 0.10208360400723113), (589, 0.09147087672458795), (590, 0.139737608412109), (591, 0.11451406826657083), (592, 0.07191347356965788), (593, 0.08768918676237282), (594, 0.10274055352275398), (595, 0.0), (596, 0.09057450915131403), (597, 0.046052859190059), (598, 0.08379095932769892), (599, 0.1385543394203804), (600, 0.07793208847553501), (601, 0.0753591073589511), (602, 0.0), (603, 0.049155793804139924), (604, 0.06714576793625529), (605, 0.10009368210835763), (606, 0.06525016265223525), (607, 0.14528106075155034), (608, 0.0356430194986395), (609, 0.1289412838971842), (610, 0.0), (611, 0.0942007799095625), (612, 0.06471011971826315), (613, 0.09755340560248395), (614, 0.11163025715841335), (615, 0.06392420425732688), (616, 0.10449714335307933), (617, 0.0954428728374066), (618, 0.10687297870517724), (619, 0.12549936430245173), (620, 0.07672596494963407), (621, 0.07474577375983228), (622, 0.13485839502372296), (623, 0.07755469436409518), (624, 0.12551913287811553), (625, 0.0811503514485933), (626, 0.09627544862506296), (627, 0.10861181923941295), (628, 0.10378154624520687), (629, 0.11154387036325496), (630, 0.032168260956063406), (631, 0.1424731875849849), (632, 0.11956787625707295), (633, 0.09195629850101257), (634, 0.08285911883365217), (635, 0.07179407342277706), (636, 0.10718166863317492), (637, 0.08178435453626626), (638, 0.05148449191347523), (639, 0.1134250235975095), (640, 0.0695820734209258), (641, 0.04760478269715248), (642, 0.10954480930805499), (643, 0.06348584728267415), (644, 0.0), (645, 0.0), (646, 0.0658616727577458), (647, 0.04173286415226718), (648, 0.08943057540360914), (649, 0.07446538833419004), (650, 0.10135737183134237), (651, 0.08194733430648032), (652, 0.05196003769624633), (653, 0.03462921839709058), (654, 0.05155680693521444), (655, 0.06447590600656478), (656, 0.12357834628541182), (657, 0.09209921415737254), (658, 0.08673741430813667), (659, 0.10230645037515194), (660, 0.06512501107411836), (661, 0.12516749568753166), (662, 0.1136017524101683), (663, 0.0), (664, 0.09530687594898717), (665, 0.09922305215386631), (666, 0.12593550103236534), (667, 0.09380794694255176), (668, 0.08428057102945351), (669, 0.09798659149014254), (670, 0.031109996480629887), (671, 0.10234898494481709), (672, 0.08657837620124459), (673, 0.05694294441140052), (674, 0.05445188441128305), (675, 0.10041950658291948), (676, 0.06659337463671705), (677, 0.06966638978924655), (678, 0.0), (679, 0.11515681303138915), (680, 0.09173642369064007), (681, 0.07311502250156406), (682, 0.09454618501898954), (683, 0.060493797302916825), (684, 0.0), (685, 0.10264517572964052), (686, 0.07092529107662637), (687, 0.039099610353676345), (688, 0.06286440966829114), (689, 0.05023382638282907), (690, 0.05308868506956419), (691, 0.04789860110654712), (692, 0.0), (693, 0.10809281674286786), (694, 0.07284066090372975), (695, 0.10004716197216512), (696, 0.07467424632429367), (697, 0.02543089747127929), (698, 0.09935859810986877), (699, 0.06943853159538506), (700, 0.04911430823216411), (701, 0.10679647793334124), (702, 0.11687753941344575), (703, 0.07011922909742999), (704, 0.0), (705, 0.07438371610946165), (706, 0.0), (707, 0.06667304700202709), (708, 0.12089319061959035), (709, 0.0847922968559892), (710, 0.08189075500366227), (711, 0.061219625619786194), (712, 0.07952305223112784), (713, 0.0), (714, 0.07207901481431775), (715, 0.07222521328809729), (716, 0.05923576400359612), (717, 0.06311694986568668), (718, 0.06385003523506581), (719, 0.0), (720, 0.07603294938622107), (721, 0.0), (722, 0.23136300897526715), (723, 0.0959054733123599), (724, 0.13036007154344798), (725, 0.08150482064437366), (726, 0.07019714647804745), (727, 0.0), (728, 0.09033499941678039), (729, 0.12779565488081385), (730, 0.09203334976040435), (731, 0.02818851608427501), (732, 0.06518529204823237), (733, 0.09017890334304542), (734, 0.07917975764490863), (735, 0.0919553032040137), (736, 0.07187193321434665), (737, 0.07655736292539468), (738, 0.09730498400420358), (739, 0.03351927425911468), (740, 0.07017810892640312), (741, 0.05455212652866595), (742, 0.10805894646877348), (743, 0.09025363280293643), (744, 0.09047366259605968), (745, 0.06316368842021629), (746, 0.057115361017252675), (747, 0.11743587246081577), (748, 0.09145187954504486), (749, 0.053433397041790204), (750, 0.11632458582660886), (751, 0.07606466471355519), (752, 0.08935796863500535), (753, 0.08345423930961217), (754, 0.0412291830226911), (755, 0.0), (756, 0.07442506011842742), (757, 0.06776214273036237), (758, 0.11584257555886299), (759, 0.06325528599891383), (760, 0.12655156606571855), (761, 0.08712742280838719), (762, 0.09411819191173439), (763, 0.07598142688507584), (764, 0.07973788023142549), (765, 0.09758863724236039), (766, 0.081281684

In [ ]:
similarity_score=sorted(similarity,key=lambda x:x[1],reverse=True)
print(similarity_score)

[(1, 1.0000000000000002), (89, 0.32597780504366347), (65, 0.30960541138597036), (1644, 0.2977916477607035), (3615, 0.2665828909612806), (508, 0.25159962560184157), (1950, 0.2461366481742391), (2010, 0.24432420832834184), (2420, 0.23650424662648023), (2953, 0.2322262965144603), (722, 0.23136300897526715), (4000, 0.2227956494405782), (1211, 0.21609686918308776), (409, 0.20326395369574407), (4893, 0.2023023903928041), (377, 0.1875336303486515), (4167, 0.18612972175115838), (2274, 0.1839329909743014), (2138, 0.17985838306514743), (3236, 0.17537303859360764), (3933, 0.17113275686294527), (406, 0.16880394085345313), (2726, 0.16734970496106233), (1325, 0.16501781843736416), (123, 0.16093704034670558), (4652, 0.16014091234176475), (1547, 0.1600249587556492), (2849, 0.15874808736778442), (4062, 0.15866492424786996), (806, 0.1586169698506248), (1303, 0.15825871032239722), (911, 0.15670687979832365), (18, 0.15432318958263627), (1232, 0.15422334225723955), (3023, 0.154172734605782), (4801, 0.1539390457380266), (1019, 0.15385364827590534), (3980, 0.15299794014794682), (2247, 0.1519086315263891), (3907, 0.15141916984664064), (3437, 0.15135797795921538), (1210, 0.15096797780258808), (4453, 0.1497741774410511), (4610, 0.1492533254078854), (989, 0.14921989028863467), (811, 0.14867020329358965), (4588, 0.14849445681739018), (3015, 0.14840574918562746), (467, 0.14825090185367892), (985, 0.1480356932265244), (2562, 0.14782939124870573), (353, 0.1472519207298885), (10, 0.14685014626696033), (329, 0.14681639555765402), (1133, 0.1465634860800238), (3876, 0.14622517377585592), (2386, 0.1457870259791173), (1213, 0.14576344651341555), (1934, 0.14536378760940588), (607, 0.14528106075155034), (461, 0.14475293995591093), (768, 0.14474007508512574), (2889, 0.14470817430885477), (3786, 0.14464277841426643), (2756, 0.14460630417195747), (1136, 0.14423162523694438), (808, 0.1440946160518644), (1861, 0.14354968807886137), (1606, 0.14320952710046472), (2731, 0.14303352517479614), (631, 0.1424731875849849), (922, 0.14199996087029065), (4318, 0.1419149088569688), (3068, 0.14188884370942206), (339, 0.1415048928097842), (391, 0.14106504871420464), (1873, 0.1409785680638447), (193, 0.14090032671484032), (2598, 0.1408093894435352), (3382, 0.14072550471311554), (2540, 0.14059699058730418), (386, 0.14024732995523564), (482, 0.13993458261449487), (517, 0.1398773796300209), (590, 0.139737608412109), (2566, 0.13904953677015866), (152, 0.1389512370665247), (3006, 0.13872926336133826), (2126, 0.13863761174687225), (599, 0.1385543394203804), (165, 0.1384331439182989), (770, 0.13813787057505958), (1343, 0.13792433290201625), (2279, 0.1376932442635935), (3473, 0.13721941232958412), (4846, 0.13707306709466824), (1426, 0.1369223952363698), (1091, 0.13673710169411615), (2651, 0.1365453805902569), (1172, 0.1363007469757492), (1222, 0.1360523227429567), (841, 0.13605044623832144), (523, 0.135926239732184), (3262, 0.13571603596326753), (1903, 0.13511557723900947), (232, 0.13486109834486867), (622, 0.13485839502372296), (1911, 0.13386581227895666), (1076, 0.1336631836301595), (2418, 0.1334460270062979), (1712, 0.1332320258593804), (3282, 0.13319630543889097), (4611, 0.13314828220317437), (583, 0.1329413529745326), (2382, 0.13239433301056416), (1367, 0.1322901817185859), (2614, 0.13213145790448805), (1372, 0.1319295375435684), (392, 0.13188898306255484), (310, 0.13188132666599553), (2432, 0.13155809287555673), (4688, 0.13135132464511834), (4795, 0.13134205782126257), (370, 0.13120346368524502), (995, 0.13118703017806224), (385, 0.13118267559441843), (973, 0.13085685886611667), (3353, 0.13082073792762827), (724, 0.13036007154344798), (455, 0.13019734342384265), (3502, 0.12995816440408187), (858, 0.12994357110294627), (2851, 0.12945829252562896), (1056, 0.12940573464414004), (281, 0.12918545555127114), (1129, 0.1291549758268199), (609, 0.1289412838971842), (132, 0.12880992981066966), (1023, 0.12871341037126408), (1081, 0.1287027168117986), (301, 0.1286320617694508), (497, 0.12856418027458139), (1117, 0.12844195304406864), (846, 0.1281818190634143), (2734, 0.12815670199490245), (283, 0.1281455458704588), (3311, 0.12811875773957335), (215, 0.12808587238633326), (405, 0.12806271216469797), (1596, 0.12805548792000007), (729, 0.12779565488081385), (1450, 0.12776349126272563), (4808, 0.12775466659559653), (1251, 0.12772022190073815), (1075, 0.12755574527059294), (792, 0.12730891511174766), (2262, 0.12717343765016936), (2703, 0.12716641549585433), (3558, 0.1271654112728825), (1920, 0.12713568498080066), (3159, 0.12712511049194958), (233, 0.12696481036989807), (95, 0.12691684231013453), (1182, 0.12679312054100658), (760, 0.12655156606571855), (2590, 0.12654786041330837), (2364, 0.1264825748054673), (1141, 0.12626638227482204), (4081, 0.12611217536747885), (311, 0.1260912086137809), (666, 0.12593550103236534), (4378, 0.1258992039086872), (543, 0.12584820489801934), (153, 0.1258474724935111), (4689, 0.12580992403998204), (3108, 0.12573645225593716), (2076, 0.1256611134268773), (624, 0.12551913287811553), (619, 0.12549936430245173), (3698, 0.125445174935807), (3650, 0.12543616359366191), (0, 0.12537786008891097), (117, 0.12517564330467776), (661, 0.12516749568753166), (962, 0.12500429831806364), (229, 0.1248496107222197), (1696, 0.1246893758781153), (856, 0.12449284845461961), (2692, 0.1243807395206859), (401, 0.12419313501381393), (290, 0.12417995580037308), (363, 0.12392478035371499), (1768, 0.12389289092723499), (2518, 0.12376801175573666), (166, 0.12362064889231099), (1910, 0.12357998686723638), (656, 0.12357834628541182), (2186, 0.12357225725390743), (4196, 0.12349316052629751), (1195, 0.1233393112753456), (572, 0.12330384501857902), (131, 0.12318322744447467), (428, 0.12307270609099864), (495, 0.12306783675390984), (1214, 0.12289161859603007), (2309, 0.12282497812011015), (4154, 0.12276833216426447), (149, 0.12275876464411171), (934, 0.12275656923692158), (1952, 0.12271530252432133), (183, 0.12268746471212694), (1593, 0.12266612157239963), (4695, 0.12265259126992245), (3635, 0.12254434209331941), (3976, 0.12253477452349724), (421, 0.12250350270169047), (3025, 0.12246530636075455), (2972, 0.12235700876205652), (4273, 0.12228754289868395), (4715, 0.1222632418290651), (1823, 0.12223159215496053), (43, 0.12221980992546944), (473, 0.12215832881152563), (3018, 0.12211644987629218), (3544, 0.12207822524159745), (4095, 0.12184992490101813), (1143, 0.12169629969784), (796, 0.12160568716643166), (2530, 0.12160369889315077), (2383, 0.12158970713476747), (2261, 0.12150816856411155), (3078, 0.12147832870697561), (3765, 0.12147815109325281), (73, 0.12146562317250656), (511, 0.12101184906588072), (2039, 0.12100832650083194), (708, 0.12089319061959035), (384, 0.12088214047392266), (2221, 0.12075094732143848), (1295, 0.12064569688835249), (2738, 0.12040235010309074), (2264, 0.12027747466480898), (16, 0.12018546762764273), (4, 0.12012450636456395), (1608, 0.12011324333657991), (375, 0.11989899141422818), (416, 0.11989879796616852), (3276, 0.11989172078030216), (4523, 0.11987436493152508), (4924, 0.11986446741074194), (4824, 0.11985964317720542), (1398, 0.11985094654647037), (4902, 0.11979399308513232), (1949, 0.11966062588920978), (3383, 0.11965976587165378), (1445, 0.11964099216226637), (861, 0.11958830531203306), (632, 0.11956787625707295), (2645, 0.1195296695028126), (2072, 0.11945672553933047), (898, 0.11941024465445034), (360, 0.11930276924034983), (1283, 0.11928970893450655), (1157, 0.11915664682538804), (271, 0.11914892635929632), (2312, 0.11910971728456857), (40, 0.11893547683197873), (1762, 0.1187671339683167), (180, 0.11874825711371623), (136, 0.11866766304572582), (1196, 0.11861567842794316), (4355, 0.11852350430057536), (3468, 0.11839329104115075), (4094, 0.1183130893165443), (2896, 0.11816367927577126), (3102, 0.1181373256854597), (1507, 0.11805498983729196), (4020, 0.1180322854075403), (2551, 0.11802185743808272), (178, 0.1180092824958443), (2864, 0.11795729713048557), (4118, 0.11771397131495319), (56, 0.11769511302411313), (4455, 0.11764650367683101), (747, 0.11743587246081577), (168, 0.11741514236506366), (1106, 0.11739150082404998), (901, 0.11737300673645984), (23, 0.117288568351024), (305, 0.11725693605666099), (2026, 0.11723693925941428), (1044, 0.11720403093794352), (1765, 0.11711337710191852), (331, 0.11708815495545144), (297, 0.11703294156216797), (52, 0.11701141039107989), (4187, 0.11701082183064623), (776, 0.11700157306076096), (3273, 0.11699634125739648), (2105, 0.11696361896926212), (702, 0.11687753941344575), (48, 0.11670117275254174), (1459, 0.11662777519219711), (1807, 0.11653391962414968), (3737, 0.11643607531130808), (2343, 0.11642863335797049), (2034, 0.11642251219426897), (750, 0.11632458582660886), (4065, 0.11619745111527928), (3501, 0.11618289156332001), (345, 0.11615074217896534), (3927, 0.11612467112058254), (3412, 0.1160036732503346), (2031, 0.11594158395173725), (459, 0.11593814344108382), (758, 0.11584257555886299), (2052, 0.11577577445451362), (1626, 0.1157660262686021), (1735, 0.11571236978973623), (1001, 0.11566799820111619), (341, 0.11566000114142183), (362, 0.11562145119365234), (14, 0.11558671979331092), (3946, 0.11553233139893349), (4170, 0.11548869579082008), (4952, 0.11542947184930713), (515, 0.11541529944321971), (1110, 0.115216994203173), (679, 0.11515681303138915), (2743, 0.11505931779775674), (3143, 0.11490193970910527), (236, 0.11489039669643696), (1504, 0.1148507914706853), (1578, 0.11483351717299378), (1510, 0.11478624740642297), (9, 0.11469261298857271), (3411, 0.11467442597220266), (357, 0.11464620720181386), (1826, 0.11463121571901812), (2698, 0.11457802430836664), (591, 0.11451406826657083), (195, 0.11447838246727994), (226, 0.11445092632055802), (2268, 0.1143687150975539), (3237, 0.11436429150434724), (2660, 0.11435472295699453), (1282, 0.11434457509987975), (4537, 0.11430349468945461), (3427, 0.1142990160713572), (150, 0.11429449542993189), (2842, 0.11417813565645185), (1890, 0.11416072500798034), (2721, 0.11408295629981156), (2490, 0.11403190119711674), (1335, 0.11401792436532203), (426, 0.11396738250760406), (1619, 0.11389009034784175), (3547, 0.11383944973634953), (2606, 0.11383135001363455), (144, 0.11377013019778211), (2088, 0.11376530325374797), (222, 0.11376177282223825), (3339, 0.11375280641535188), (2478, 0.1136983182665744), (662, 0.1136017524101683), (3472, 0.11355662327908253), (2967, 0.11351783688655677), (333, 0.1135026077832193), (639, 0.1134250235975095), (1451, 0.1133330291992802), (1093, 0.11326176869793411), (777, 0.11324883971807388), (1942, 0.11320467551533839), (983, 0.1131959209888512), (295, 0.11310229841080131), (3856, 0.11308595976889829), (2925, 0.11306035004402648), (505, 0.11304413422481698), (3531, 0.11301818810007554), (895, 0.11289666041780476), (3123, 0.11280620241173309), (4613, 0.11270599935078345), (1442, 0.11263277890424757), (4889, 0.11260581904765785), (122, 0.11260110899427443), (3375, 0.11249159825393405), (367, 0.11241438823278835), (1432, 0.11220354720797368), (1250, 0.11217813344488994), (217, 0.1121471490624159), (141, 0.11205310047750795), (2348, 0.11184618847079389), (1053, 0.11184262759979625), (1458, 0.1117926163376644), (4547, 0.11174742832918555), (2211, 0.11172452708682075), (343, 0.1116855897646145), (1666, 0.11164598404467876), (614, 0.11163025715841335), (2319, 0.11162823509406496), (1794, 0.11159701782411109), (2921, 0.11159507535208806), (629, 0.11154387036325496), (1465, 0.11146574289931244), (1090, 0.11145841693544885), (4367, 0.11136459860521798), (513, 0.11130598058950217), (2018, 0.11114575859069399), (20, 0.11109351539992936), (2681, 0.11092741886641357), (4718, 0.11078385352188978), (8, 0.11076300071289512), (4165, 0.11071897889646284), (223, 0.11070725491497564), (85, 0.1106192800576126), (2359, 0.11041037180725581), (214, 0.11035710450849569), (1524, 0.11035602501866192), (2405, 0.11029851779172567), (1183, 0.11020141200954403), (1983, 0.11017987170833915), (1027, 0.11016295406665448), (3954, 0.1100996453681421), (4203, 0.11003863866599449), (1219, 0.11000745715732449), (3125, 0.10998759458531589), (234, 0.10993145358492928), (4395, 0.10988788215628313), (2173, 0.10983272877546094), (465, 0.10978705526175177), (1417, 0.10975147050660608), (2086, 0.10974903652098048), (516, 0.10969714484104658), (3498, 0.10966416484423308), (439, 0.1096628544617252), (3274, 0.10963632917684427), (4368, 0.10962138053070358), (970, 0.10958731454756959), (642, 0.10954480930805499), (2392, 0.10953116300807834), (863, 0.10943346243645188), (1003, 0.10941409741097656), (4491, 0.10936755821692604), (35, 0.10935267603970016), (4531, 0.10933263066523301), (1636, 0.10932231214829169), (1998, 0.1092358295369456), (2829, 0.10918269133093865), (3289, 0.10917587148049153), (2125, 0.1091657659031098), (3251, 0.10914219705243713), (1248, 0.10906938924217546), (3504, 0.10904364335369211), (1294, 0.10902010608153298), (1162, 0.1089662497693934), (1258, 0.10895586910523987), (4116, 0.10889579157139416), (3182, 0.10888122506575638), (94, 0.10887956773033432), (2163, 0.10884812169038645), (2283, 0.10881647275414215), (346, 0.10880382528050613), (627, 0.10861181923941295), (113, 0.10860931610235812), (2589, 0.10835285173824262), (4592, 0.10833958715421378), (4385, 0.10832717334308993), (4713, 0.10829359910895872), (3923, 0.10825407229724887), (2515, 0.10824380873193507), (4575, 0.108241216716876), (3224, 0.10812668250604932), (2713, 0.10810330876514998), (1631, 0.10809713217094417), (3655, 0.10809430121390996), (693, 0.10809281674286786), (742, 0.10805894646877348), (3, 0.1080510615817161), (775, 0.10803705216820972), (2276, 0.10801349565187436), (4901, 0.10800498995233548), (187, 0.10794386690293134), (91, 0.10793066966825826), (821, 0.10789667902821026), (3005, 0.10788911499758169), (336, 0.10786958724821873), (1312, 0.10784364175395378), (1927, 0.10784040040944322), (840, 0.10777389578787526), (1350, 0.10769147653408016), (4939, 0.10768836226161595), (93, 0.107684572071173), (1834, 0.10754937853133643), (252, 0.10754501707196723), (12, 0.10751428497661301), (2778, 0.1075006574712207), (3862, 0.10740853297059623), (2177, 0.10737448122651445), (1187, 0.10734166674549332), (75, 0.10734121513719645), (4818, 0.10731400237324676), (312, 0.10729491854577904), (4865, 0.10728893951281868), (22, 0.10728615394841404), (3416, 0.10719868858885002), (116, 0.10719269171859087), (636, 0.10718166863317492), (4243, 0.10715760762974584), (1466, 0.10708958945431069), (1580, 0.10707466978604945), (303, 0.10706090519969483), (1492, 0.10701537620051312), (3310, 0.10699338541362488), (118, 0.10689632690320391), (101, 0.1068930140228982), (3507, 0.10687509456156429), (618, 0.10687297870517724), (4552, 0.10684343214558607), (1519, 0.10680333893863377), (4642, 0.10680262818154206), (3624, 0.10679907180145755), (701, 0.10679647793334124), (1127, 0.1066838258953263), (1683, 0.10664534814408841), (2974, 0.1066450773041423), (1414, 0.10660394815620322), (2311, 0.10659745788468104), (1094, 0.10658100736424456), (205, 0.1065587703659133), (1573, 0.10655394335399987), (2048, 0.10654294677551701), (2684, 0.106531364429082), (2940, 0.10651023541897679), (2174, 0.10649651007507775), (938, 0.10646527233217443), (4168, 0.10642843056550942), (422, 0.10642488322247365), (4353, 0.10636352786142976), (1267, 0.10626300394598474), (1625, 0.10626121155472444), (1938, 0.10618225810387871), (1154, 0.10608682172370708), (4276, 0.1060850948376457), (787, 0.10607202257352515), (158, 0.1060485172573262), (2454, 0.10602534497157944), (1359, 0.10601290787971823), (269, 0.10599466977247905), (1497, 0.10599276920682432), (447, 0.10592653092243191), (1304, 0.10584809162564314), (2492, 0.10575073705882115), (2989, 0.10574110886196493), (894, 0.10572696333938439), (557, 0.10570514890142074), (185, 0.10570443446076833), (3320, 0.1056839395373126), (4498, 0.10567816736885778), (4003, 0.10566403046469039), (317, 0.10563833181369528), (2693, 0.10563824002108826), (299, 0.1056099043662801), (1012, 0.105599517341568), (4494, 0.10559660628119011), (939, 0.10555313523610674), (3675, 0.10552332460134363), (2656, 0.10540430745750831), (2657, 0.10534416127062685), (2826, 0.10533044273151172), (1862, 0.10532293583586), (442, 0.10524588351224197), (4161, 0.1052355688886813), (3017, 0.10523224379258687), (1590, 0.10519047016420867), (2066, 0.10502390449973006), (860, 0.10502313060826313), (1055, 0.10501266071935363), (498, 0.10496281013972877), (2089, 0.10487548698375176), (1598, 0.10478649076551179), (3362, 0.10472676701823998), (1850, 0.10471091478909676), (2964, 0.10470384966753721), (1797, 0.104687704981155), (1880, 0.10468542785761817), (1552, 0.10463341040035704), (1852, 0.10462765060061084), (294, 0.10462470974531567), (4075, 0.10461629865652769), (1912, 0.1045565843389034), (1288, 0.10452240605433805), (616, 0.10449714335307933), (578, 0.10446333847997673), (570, 0.10443899770598192), (335, 0.10439622771669374), (4510, 0.10439364326476835), (837, 0.1043893989256456), (947, 0.10433961943326774), (774, 0.10431011145037372), (130, 0.10419080234122959), (2474, 0.10408240753360297), (2241, 0.1040747084042185), (1191, 0.10403952729595313), (1217, 0.1039960795039956), (4448, 0.10392540592875718), (1588, 0.10391709326985475), (843, 0.10388871068163816), (3297, 0.10383458441054165), (3652, 0.10381459984923855), (3499, 0.10381196139765576), (804, 0.10379612878705644), (628, 0.10378154624520687), (2350, 0.10364869626377655), (2664, 0.10358069890532502), (3328, 0.10353513528515748), (292, 0.10334021154770769), (1059, 0.10333838709651083), (3036, 0.10332053655014534), (1046, 0.10327469078044757), (1374, 0.10321409260480653), (3727, 0.1031757337382645), (2272, 0.10316906195527495), (3567, 0.10316140372659832), (4898, 0.10315824782610315), (2697, 0.10311783384422768), (1447, 0.10303856512989336), (1358, 0.10303501860686011), (2094, 0.10302891879301027), (1616, 0.10298933475921279), (3305, 0.10297271053287008), (1621, 0.1029680163551572), (126, 0.1029061953719346), (24, 0.10289865935254873), (1627, 0.1028593520359836), (4734, 0.10276579033536472), (594, 0.10274055352275398), (3679, 0.10270738404624621), (1357, 0.10266898271124636), (373, 0.10265807830113363), (685, 0.10264517572964052), (4177, 0.10263682584069758), (4485, 0.10261346415484084), (1146, 0.10257479451728872), (474, 0.10256003929036174), (4559, 0.10254922489651766), (825, 0.1025451935999382), (4312, 0.10254354369693724), (1087, 0.10246363300637909), (4404, 0.10245060883712154), (2087, 0.10241851363015964), (671, 0.10234898494481709), (196, 0.10233469755874924), (659, 0.10230645037515194), (1324, 0.10229208326727754), (2325, 0.10208595727023376), (588, 0.10208360400723113), (3909, 0.10206044556363462), (1544, 0.1020419735179927), (402, 0.10204136357541393), (400, 0.10203256809696694), (3884, 0.1020141514361504), (1915, 0.10199756315015719), (2197, 0.10198934456844358), (996, 0.10194376931742634), (4723, 0.1019069588159869), (1361, 0.10184403345278129), (2844, 0.10182985076262949), (2398, 0.1017449464408698), (4232, 0.10173964142424163), (419, 0.10170822229799742), (253, 0.1016972529195597), (1830, 0.1016827700272995), (1932, 0.10163593215722641), (1147, 0.10160391920886049), (4737, 0.10158178557347519), (1234, 0.10154631811183917), (1812, 0.10147829098802928), (3185, 0.1014755567175094), (4006, 0.10146797532255207), (1673, 0.10141525051761187), (4059, 0.10140265655956435), (480, 0.10140014793349524), (2157, 0.10135879197350586), (781, 0.1013579464222393), (650, 0.10135737183134237), (1967, 0.10135025088539378), (3664, 0.10132110006166335), (3546, 0.10131254468364397), (2378, 0.10130033018302292), (1095, 0.10130021152450934), (3094, 0.10129917370031315), (1599, 0.10128368321349522), (203, 0.10127254963743045), (2231, 0.1012359973946806), (414, 0.10123306162673425), (1185, 0.10121937370127214), (2256, 0.10114793959053381), (3205, 0.10098911363116646), (36, 0.10095581335173964), (3354, 0.1009150284397212), (1040, 0.10091112269145076), (344, 0.10090417914987124), (3067, 0.10085922769065588), (881, 0.10078151325373222), (3162, 0.

In [ ]:
count=1
for i in similarity_score:
  num=i[0]
  GAMES=dataset[dataset.index==num]['name'].values[0]
  if count<=10:
    print(count,GAMES)
    count=count+1

1 PLAYERUNKNOWN'S BATTLEGROUNDS
2 Ring of Elysium
3 Realm Royale
4 Z1 Battle Royale
5 Geneshift Royale
6 Totally Accurate Battlegrounds
7 Cuisine Royale
8 STAND OUT : VR Battle Royale
9 Infestation: The New Z
10 Battle Royale Tycoon